name: GitHub Actions
run-name: Go test sample
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  
      - run: go get ${{ github.workspace }}/manager 
      - run: go test -run ^TestGetServiceDir$ ${{ github.workspace }}/manager/container