name: GitHub Actions
run-name: Go test sample
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'  
      - run: go get ./manager/ 
      - run: go test 