name: GitHub Actions
run-name: Go test sample
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20']
    steps:
      - uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}/manager/container
      - run: go test -run ^TestGetServiceDir$ ./manager/container